// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRiB0zkoRxp126e0rZ-X0TpYjP5NcM7AQ',
    appId: '1:595682801767:web:2285180bcddd98f0ea7cc2',
    messagingSenderId: '595682801767',
    projectId: 'universitycommunity-6ae90',
    authDomain: 'universitycommunity-6ae90.firebaseapp.com',
    storageBucket: 'universitycommunity-6ae90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBGNUMzQWQjKxsrslZLStx4KFEENamzE',
    appId: '1:595682801767:android:edffd7fc207cb3b6ea7cc2',
    messagingSenderId: '595682801767',
    projectId: 'universitycommunity-6ae90',
    storageBucket: 'universitycommunity-6ae90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-Bbw0SxI8UC0JQZ2dtJsGJLG0LaKw7I',
    appId: '1:595682801767:ios:13cf8e541cb16690ea7cc2',
    messagingSenderId: '595682801767',
    projectId: 'universitycommunity-6ae90',
    storageBucket: 'universitycommunity-6ae90.firebasestorage.app',
    iosBundleId: 'com.example.bluenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0-Bbw0SxI8UC0JQZ2dtJsGJLG0LaKw7I',
    appId: '1:595682801767:ios:13cf8e541cb16690ea7cc2',
    messagingSenderId: '595682801767',
    projectId: 'universitycommunity-6ae90',
    storageBucket: 'universitycommunity-6ae90.firebasestorage.app',
    iosBundleId: 'com.example.bluenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRiB0zkoRxp126e0rZ-X0TpYjP5NcM7AQ',
    appId: '1:595682801767:web:c2ead1692157b9ecea7cc2',
    messagingSenderId: '595682801767',
    projectId: 'universitycommunity-6ae90',
    authDomain: 'universitycommunity-6ae90.firebaseapp.com',
    storageBucket: 'universitycommunity-6ae90.firebasestorage.app',
  );
}
